// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNgd8S1pg_o_73BvNS1pDUhrAGbwRG3XU',
    appId: '1:425327861004:web:acbf141f8ca0cd1f553d29',
    messagingSenderId: '425327861004',
    projectId: 'fsds-d1979',
    authDomain: 'fsds-d1979.firebaseapp.com',
    storageBucket: 'fsds-d1979.firebasestorage.app',
    measurementId: 'G-3W5P9LKB11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASNFQnljpwU09rQKynjsd1Y3MafMy6dSQ',
    appId: '1:425327861004:android:db5663ed05c43f4b553d29',
    messagingSenderId: '425327861004',
    projectId: 'fsds-d1979',
    storageBucket: 'fsds-d1979.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3QEPfmlwAub8URCFsHftA1RWLpYbepPM',
    appId: '1:425327861004:ios:7517f1dd095b3ad6553d29',
    messagingSenderId: '425327861004',
    projectId: 'fsds-d1979',
    storageBucket: 'fsds-d1979.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3QEPfmlwAub8URCFsHftA1RWLpYbepPM',
    appId: '1:425327861004:ios:7517f1dd095b3ad6553d29',
    messagingSenderId: '425327861004',
    projectId: 'fsds-d1979',
    storageBucket: 'fsds-d1979.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNgd8S1pg_o_73BvNS1pDUhrAGbwRG3XU',
    appId: '1:425327861004:web:2e563bae77d1959b553d29',
    messagingSenderId: '425327861004',
    projectId: 'fsds-d1979',
    authDomain: 'fsds-d1979.firebaseapp.com',
    storageBucket: 'fsds-d1979.firebasestorage.app',
    measurementId: 'G-EQSMX0NM8Q',
  );
}
